### ISSUE TITLE
Bright event banner on chat.SE

### ISSUE THREAD

**Issue by mvarendorff** [MadaraUchiha/se-chat-dark-theme-plus#21]
The event banner on https://chat.stackexchange.com/ contains CSS to have a bright background:

![grafik](https://user-images.githubusercontent.com/26303198/66741745-7e0f6300-ee76-11e9-8e86-5b0a4a386ae1.png)

The fix should be as simple as 

```css
.event-banner {
    background: unset;
}
```

but I wasn't sure in which of the many scss files to put it.
